/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caficultor;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cadefihuilaltda
 */
public class CaficultorFRM extends javax.swing.JFrame {

    /**
     * Creates new form CaficultorFRM
     */
    private DefaultTableModel modeloTablaCaficultor;
    public CaficultorFRM() {
        modeloTablaCaficultor = new DefaultTableModel(null, getColumn());
        initComponents();
        cargarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String[] getColumn(){
        String columnas[] = new String[]{"Identificacion", "Tipo Identificacion","Nombres", "Apellidos", "Teléfono","Dirección","Email", "Ciudad","Sexo","Estado"};
        return columnas;
    }
    
    private void cargarTabla(){
        Caficultor objPersona = new Caficultor();
        ResultSet resultado = objPersona.cargarTablaCaficultor();
        try{
            Object dato[] = new Object[10];
            while(resultado.next()){
                for(int i = 0; i < 10;i++){
                dato[i] = resultado.getObject(i+1);
                }
            modeloTablaCaficultor.addRow(dato);
            }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Ocurrio un error: "+ex.getMessage());
        }
    }
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCaf_identificacion = new javax.swing.JLabel();
        lblCaf_tipo_identificacion = new javax.swing.JLabel();
        lblCaf_nombres = new javax.swing.JLabel();
        lbl_Caf_apellidos = new javax.swing.JLabel();
        lblCaf_telefono = new javax.swing.JLabel();
        lblCaf_direccion = new javax.swing.JLabel();
        lblCaf_ubicacion = new javax.swing.JLabel();
        lblCaf_sexo = new javax.swing.JLabel();
        lblCaf_estado = new javax.swing.JLabel();
        txtCaf_identificacion = new javax.swing.JTextField();
        txtCaf_tipo_identificacion = new javax.swing.JTextField();
        txtCaf_nombres = new javax.swing.JTextField();
        txtCaf_apellidos = new javax.swing.JTextField();
        txtCaf_telefono = new javax.swing.JTextField();
        txtCaf_direccion = new javax.swing.JTextField();
        txtCaf_ubicacion = new javax.swing.JTextField();
        txtCaf_sexo = new javax.swing.JTextField();
        txtCaf_estado = new javax.swing.JTextField();
        lbl_Caf_email = new javax.swing.JLabel();
        txtCaf_email = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCaficultor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCaf_identificacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCaf_identificacion.setText("Identificación:");

        lblCaf_tipo_identificacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_tipo_identificacion.setText("Tipo de Identificación:");

        lblCaf_nombres.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_nombres.setText("Nombres Caficultor:");

        lbl_Caf_apellidos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_Caf_apellidos.setText("Apellidos Caficultor:");

        lblCaf_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_telefono.setText("Teléfono:");

        lblCaf_direccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_direccion.setText("Dirección:");

        lblCaf_ubicacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_ubicacion.setText("Ciudad:");

        lblCaf_sexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_sexo.setText("Sexo:");

        lblCaf_estado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaf_estado.setText("Estado:");

        txtCaf_identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_identificacion.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_tipo_identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_tipo_identificacion.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_nombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_nombres.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_apellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_apellidos.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_telefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_telefono.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_direccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_direccion.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_ubicacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_ubicacion.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_sexo.setForeground(new java.awt.Color(0, 0, 153));

        txtCaf_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_estado.setForeground(new java.awt.Color(0, 0, 153));

        lbl_Caf_email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_Caf_email.setText("Email:");

        txtCaf_email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCaf_email.setForeground(new java.awt.Color(0, 0, 153));

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(153, 0, 0));
        btnEliminar.setText("Eliminar");

        jtbCaficultor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtbCaficultor.setForeground(new java.awt.Color(0, 0, 102));
        jtbCaficultor.setModel(modeloTablaCaficultor);
        jScrollPane1.setViewportView(jtbCaficultor);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caficultores");

        btnModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 97, 47));
        btnModificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Caf_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_tipo_identificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbCaf_identificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_nombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Caf_apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_ubicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_sexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCaf_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnGuardar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCaf_identificacion)
                                    .addComponent(txtCaf_tipo_identificacion)
                                    .addComponent(txtCaf_nombres)
                                    .addComponent(txtCaf_apellidos)
                                    .addComponent(txtCaf_telefono)
                                    .addComponent(txtCaf_direccion)
                                    .addComponent(txtCaf_ubicacion)
                                    .addComponent(txtCaf_sexo)
                                    .addComponent(txtCaf_estado)
                                    .addComponent(txtCaf_email, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(btnEliminar)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCaf_identificacion)
                            .addComponent(txtCaf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_tipo_identificacion)
                            .addComponent(txtCaf_tipo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_nombres)
                            .addComponent(txtCaf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Caf_apellidos)
                            .addComponent(txtCaf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_telefono)
                            .addComponent(txtCaf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_direccion)
                            .addComponent(txtCaf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Caf_email)
                            .addComponent(txtCaf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_ubicacion)
                            .addComponent(txtCaf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_sexo)
                            .addComponent(txtCaf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCaf_estado)
                            .addComponent(txtCaf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGuardar)
                                .addComponent(btnEliminar))
                            .addComponent(btnModificar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Caficultor objCaficultor = new Caficultor();
        int caf_identificacion =  Integer.parseInt(txtCaf_identificacion.getText());
        String caf_tipo_identificacion =txtCaf_tipo_identificacion.getText();
        String caf_nombres = txtCaf_nombres.getText();
        String caf_apellidos = txtCaf_apellidos.getText();
        int caf_telefono = Integer.parseInt(txtCaf_telefono.getText());
        String caf_direccion = txtCaf_direccion.getText();
        String caf_email = txtCaf_email.getText();
        int caf_id_ubicacion = Integer.parseInt(txtCaf_ubicacion.getText());
        String caf_sexo = txtCaf_sexo.getText();
        String caf_estado = txtCaf_estado.getText();

        
        boolean resultado = objCaficultor.insertarCaficultor(caf_identificacion,caf_tipo_identificacion,caf_nombres,caf_apellidos,caf_telefono,caf_direccion,caf_email,caf_id_ubicacion,caf_sexo,caf_estado);
        if(resultado){
            JOptionPane.showMessageDialog(null, "Se inserto correctamente.");
            modeloTablaCaficultor.setNumRows(0);
            cargarTabla();

            
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrio un error al insertar.");
        }
        //Limpiar Datos de los campos
            txtCaf_identificacion.setText("");
            txtCaf_tipo_identificacion.setText("");
            txtCaf_nombres.setText("");
            txtCaf_apellidos.setText("");
            txtCaf_telefono.setText("");
            txtCaf_direccion.setText("");
            txtCaf_email.setText("");
            txtCaf_ubicacion.setText("");
            txtCaf_sexo.setText("");
            txtCaf_estado.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaficultorFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaficultorFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaficultorFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaficultorFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaficultorFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbCaficultor;
    private javax.swing.JLabel lbCaf_identificacion;
    private javax.swing.JLabel lblCaf_direccion;
    private javax.swing.JLabel lblCaf_estado;
    private javax.swing.JLabel lblCaf_nombres;
    private javax.swing.JLabel lblCaf_sexo;
    private javax.swing.JLabel lblCaf_telefono;
    private javax.swing.JLabel lblCaf_tipo_identificacion;
    private javax.swing.JLabel lblCaf_ubicacion;
    private javax.swing.JLabel lbl_Caf_apellidos;
    private javax.swing.JLabel lbl_Caf_email;
    private javax.swing.JTextField txtCaf_apellidos;
    private javax.swing.JTextField txtCaf_direccion;
    private javax.swing.JTextField txtCaf_email;
    private javax.swing.JTextField txtCaf_estado;
    private javax.swing.JTextField txtCaf_identificacion;
    private javax.swing.JTextField txtCaf_nombres;
    private javax.swing.JTextField txtCaf_sexo;
    private javax.swing.JTextField txtCaf_telefono;
    private javax.swing.JTextField txtCaf_tipo_identificacion;
    private javax.swing.JTextField txtCaf_ubicacion;
    // End of variables declaration//GEN-END:variables
}
