/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Producto;


import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cadefihuilaltda
 */
public class ProductoFRM extends javax.swing.JFrame {

    /**
     * Creates new form CaficultorFRM
     */
    private DefaultTableModel modeloTablaProducto;
    private DefaultComboBoxModel modeloComboEstado;
    public ProductoFRM() {
        modeloTablaProducto = new DefaultTableModel(null, getColumn());
        modeloComboEstado = new DefaultComboBoxModel(new String[] {});
        
        initComponents();
        cargarTabla();
    
     
        //Listar en combobox Estado
        Producto objEstado = new Producto();
        ResultSet resEstado;
        resEstado = objEstado.cargarComboEstado();
            try {
                while(resEstado.next()){
                    modeloComboEstado.addElement(new ZoomCaracteristicas(resEstado.getString("car_codigo"),resEstado.getString("car_nombre")));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el combo de Estado de Ciudad debido a: "+e.getMessage());
            }

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String[] getColumn(){
        String columnas[] = new String[]{"Código Producto", "Nombre Producto","Estado Producto"};
        return columnas;
    }
    
    private void cargarTabla(){
        Producto objProducto = new Producto();
        ResultSet resultado = objProducto.cargarTablaProducto();
        try{
            Object dato[] = new Object[3];
            while(resultado.next()){
                for(int i = 0; i < 3;i++){
                dato[i] = resultado.getObject(i+1);
                }
            modeloTablaProducto.addRow(dato);
            }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Ocurrio un error: "+ex.getMessage());
        }
    }
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPro_id_Producto = new javax.swing.JLabel();
        lblPro_nombre = new javax.swing.JLabel();
        lblPro_estado = new javax.swing.JLabel();
        txtPro_id_Producto = new javax.swing.JTextField();
        txtPro_nombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        cmbPro_estado = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPro_id_Producto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPro_id_Producto.setText("Código Producto");

        lblPro_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPro_nombre.setText("Nombre Producto:");

        lblPro_estado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPro_estado.setText("Estado:");

        txtPro_id_Producto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPro_id_Producto.setForeground(new java.awt.Color(0, 0, 153));
        txtPro_id_Producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPro_id_ProductoKeyTyped(evt);
            }
        });

        txtPro_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPro_nombre.setForeground(new java.awt.Color(0, 0, 153));
        txtPro_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPro_nombreKeyTyped(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(153, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jtbProducto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtbProducto.setForeground(new java.awt.Color(0, 0, 102));
        jtbProducto.setModel(modeloTablaProducto);
        jScrollPane1.setViewportView(jtbProducto);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pepa_cafe.jpg"))); // NOI18N
        jLabel1.setText("Productos");

        btnModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 97, 47));
        btnModificar.setText("Modificar");

        cmbPro_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbPro_estado.setForeground(new java.awt.Color(0, 0, 102));
        cmbPro_estado.setModel(modeloComboEstado);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras_pequeño.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir_pequenio.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblPro_id_Producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPro_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(lblPro_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbPro_estado, javax.swing.GroupLayout.Alignment.LEADING, 0, 164, Short.MAX_VALUE)
                                        .addComponent(txtPro_id_Producto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPro_nombre, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardar)
                                    .addGap(22, 22, 22)
                                    .addComponent(btnModificar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEliminar)))
                            .addGap(18, 18, 18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPro_id_Producto)
                    .addComponent(txtPro_id_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPro_nombre)
                    .addComponent(txtPro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPro_estado)
                    .addComponent(cmbPro_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Producto objProducto = new Producto();
        int pro_id_producto =  Integer.parseInt(txtPro_id_Producto.getText());
        String pro_nombre = txtPro_nombre.getText();
        ZoomCaracteristicas objEstado = (ZoomCaracteristicas) cmbPro_estado.getSelectedItem();
        String pro_estado = objEstado.getCar_codigo();

        
        boolean resultado = objProducto.insertarProducto(pro_id_producto,pro_nombre,pro_estado);
        if(resultado){
            JOptionPane.showMessageDialog(null, "Se inserto correctamente el producto: " + "\n" + "- Código Producto: " + pro_id_producto+ "\n" + "- Nombre Producto: " + pro_nombre);
            modeloTablaProducto.setNumRows(0);
            cargarTabla();

            
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrio un error al insertar debido a: ");
        }
        //Limpiar Datos de los campos
            txtPro_id_Producto.setText("");
            txtPro_nombre.setText("");
            cmbPro_estado.setSelectedIndex(0);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Producto objProducto = new Producto();
         int pro_id_producto = Integer.parseInt(txtPro_id_Producto.getText());
         boolean resultado = objProducto.eliminarProducto(pro_id_producto);
         if (resultado) {
            JOptionPane.showMessageDialog(null, "Se elimino Correctamente el producto con código: "+ pro_id_producto);
            modeloTablaProducto.setNumRows(0);
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error en el Sistema con la Base de Datos");
        }
         
         //Limpiar Datos de los campos
            txtPro_id_Producto.setText("");
            txtPro_nombre.setText("");
            cmbPro_estado.setSelectedIndex(0);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPro_id_ProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPro_id_ProductoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPro_id_ProductoKeyTyped

    private void txtPro_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPro_nombreKeyTyped
        /// validaciones
    }//GEN-LAST:event_txtPro_nombreKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Inicio.Inicio verformulario2 =new Inicio.Inicio();
 
         //línea 2-hacemos visible el formulario que queremos llamar 
         verformulario2.setVisible(true); 
         setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbPro_estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbProducto;
    private javax.swing.JLabel lblPro_estado;
    private javax.swing.JLabel lblPro_id_Producto;
    private javax.swing.JLabel lblPro_nombre;
    private javax.swing.JTextField txtPro_id_Producto;
    private javax.swing.JTextField txtPro_nombre;
    // End of variables declaration//GEN-END:variables
}
