package CiudadApp;


/**
* CiudadApp/CiudadPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ciudad.idl
* lunes 27 de mayo de 2019 01:02:01 PM COT
*/

public abstract class CiudadPOA extends org.omg.PortableServer.Servant
 implements CiudadApp.CiudadOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarCiudad", new java.lang.Integer (0));
    _methods.put ("actualizarCiudad", new java.lang.Integer (1));
    _methods.put ("eliminarCiudad", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CiudadApp/Ciudad/insertarCiudad
       {
         int ubi_id_ubicacion = in.read_long ();
         String ubi_nombre = in.read_wstring ();
         String ubi_estado = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarCiudad (ubi_id_ubicacion, ubi_nombre, ubi_estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CiudadApp/Ciudad/actualizarCiudad
       {
         int ubi_id_ubicacion = in.read_long ();
         String ubi_nombre = in.read_wstring ();
         String ubi_estado = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarCiudad (ubi_id_ubicacion, ubi_nombre, ubi_estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CiudadApp/Ciudad/eliminarCiudad
       {
         int ubi_id_ubicacion = in.read_long ();
         boolean $result = false;
         $result = this.eliminarCiudad (ubi_id_ubicacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // CiudadApp/Ciudad/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CiudadApp/Ciudad:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Ciudad _this() 
  {
    return CiudadHelper.narrow(
    super._this_object());
  }

  public Ciudad _this(org.omg.CORBA.ORB orb) 
  {
    return CiudadHelper.narrow(
    super._this_object(orb));
  }


} // class CiudadPOA
