package CiudadApp;


/**
* CiudadApp/CiudadOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ciudad.idl
* lunes 27 de mayo de 2019 01:02:01 PM COT
*/

public interface CiudadOperations 
{
  boolean insertarCiudad (int ubi_id_ubicacion, String ubi_nombre, String ubi_estado);
  boolean actualizarCiudad (int ubi_id_ubicacion, String ubi_nombre, String ubi_estado);
  boolean eliminarCiudad (int ubi_id_ubicacion);
  void shutdown ();
} // interface CiudadOperations
