package CiudadApp;

/**
* CiudadApp/CiudadHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ciudad.idl
* lunes 27 de mayo de 2019 01:02:01 PM COT
*/

public final class CiudadHolder implements org.omg.CORBA.portable.Streamable
{
  public CiudadApp.Ciudad value = null;

  public CiudadHolder ()
  {
  }

  public CiudadHolder (CiudadApp.Ciudad initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CiudadApp.CiudadHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CiudadApp.CiudadHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CiudadApp.CiudadHelper.type ();
  }

}
