package CaficultorApp;


/**
* CaficultorApp/_CaficultorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Caficultor.idl
* lunes 20 de mayo de 2019 12:19:22 AM COT
*/

public class _CaficultorStub extends org.omg.CORBA.portable.ObjectImpl implements CaficultorApp.Caficultor
{

  public boolean insertarCaficultor (int caf_identificacion, String caf_tipo_identificacion, String caf_nombres, String caf_apellidos, int caf_telefono, String caf_direccion, String caf_email, int caf_id_ubicacion, String caf_sexo, String caf_estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarCaficultor", true);
                $out.write_long (caf_identificacion);
                $out.write_wstring (caf_tipo_identificacion);
                $out.write_wstring (caf_nombres);
                $out.write_wstring (caf_apellidos);
                $out.write_long (caf_telefono);
                $out.write_wstring (caf_direccion);
                $out.write_wstring (caf_email);
                $out.write_long (caf_id_ubicacion);
                $out.write_wstring (caf_sexo);
                $out.write_wstring (caf_estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarCaficultor (caf_identificacion, caf_tipo_identificacion, caf_nombres, caf_apellidos, caf_telefono, caf_direccion, caf_email, caf_id_ubicacion, caf_sexo, caf_estado        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarCaficultor

  public boolean actualizarCaficultor (int caf_identificacion, String caf_tipo_identificacion, String caf_nombres, String caf_apellidos, int caf_telefono, String caf_direccion, int caf_id_ubicacion, String caf_email, String caf_sexo, String caf_estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarCaficultor", true);
                $out.write_long (caf_identificacion);
                $out.write_wstring (caf_tipo_identificacion);
                $out.write_wstring (caf_nombres);
                $out.write_wstring (caf_apellidos);
                $out.write_long (caf_telefono);
                $out.write_wstring (caf_direccion);
                $out.write_long (caf_id_ubicacion);
                $out.write_wstring (caf_email);
                $out.write_wstring (caf_sexo);
                $out.write_wstring (caf_estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarCaficultor (caf_identificacion, caf_tipo_identificacion, caf_nombres, caf_apellidos, caf_telefono, caf_direccion, caf_id_ubicacion, caf_email, caf_sexo, caf_estado        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarCaficultor

  public boolean eliminarCaficultor (int caf_identificacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarCaficultor", true);
                $out.write_long (caf_identificacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarCaficultor (caf_identificacion        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarCaficultor

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CaficultorApp/Caficultor:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CaficultorStub
