package CaficultorApp;


/**
* CaficultorApp/_CaficultorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from caficultor.idl
* domingo 12 de mayo de 2019 10:01:11 PM COT
*/

public class _CaficultorStub extends org.omg.CORBA.portable.ObjectImpl implements CaficultorApp.Caficultor
{

  public boolean insertarPersona (int identificacion, char tipo_identificacion, String nombres, String apellidos, int telefono, String direccion, int ubicacion, char sexo, char estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarPersona", true);
                $out.write_long (identificacion);
                $out.write_char (tipo_identificacion);
                $out.write_wstring (nombres);
                $out.write_wstring (apellidos);
                $out.write_long (telefono);
                $out.write_wstring (direccion);
                $out.write_long (ubicacion);
                $out.write_char (sexo);
                $out.write_char (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarPersona (identificacion, tipo_identificacion, nombres, apellidos, telefono, direccion, ubicacion, sexo, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarPersona

  public boolean actualizarPersona (int identificacion, char tipo_identificacion, String nombres, String apellidos, int telefono, String direccion, int ubicacion, char sexo, char estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarPersona", true);
                $out.write_long (identificacion);
                $out.write_char (tipo_identificacion);
                $out.write_wstring (nombres);
                $out.write_wstring (apellidos);
                $out.write_long (telefono);
                $out.write_wstring (direccion);
                $out.write_long (ubicacion);
                $out.write_char (sexo);
                $out.write_char (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarPersona (identificacion, tipo_identificacion, nombres, apellidos, telefono, direccion, ubicacion, sexo, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarPersona

  public boolean eliminarPersona (int identificacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarPersona", true);
                $out.write_long (identificacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarPersona (identificacion        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarPersona

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CaficultorApp/Caficultor:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CaficultorStub
