package CaficultorApp;


/**
* CaficultorApp/CaficultorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from caficultor.idl
* domingo 12 de mayo de 2019 10:01:11 PM COT
*/

public interface CaficultorOperations 
{
  boolean insertarPersona (int identificacion, char tipo_identificacion, String nombres, String apellidos, int telefono, String direccion, int ubicacion, char sexo, char estado);
  boolean actualizarPersona (int identificacion, char tipo_identificacion, String nombres, String apellidos, int telefono, String direccion, int ubicacion, char sexo, char estado);
  boolean eliminarPersona (int identificacion);
  void shutdown ();
} // interface CaficultorOperations
