package CaficultorApp;


/**
* CaficultorApp/CaficultorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Caficultor.idl
* lunes 20 de mayo de 2019 12:19:22 AM COT
*/

abstract public class CaficultorHelper
{
  private static String  _id = "IDL:CaficultorApp/Caficultor:1.0";

  public static void insert (org.omg.CORBA.Any a, CaficultorApp.Caficultor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CaficultorApp.Caficultor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CaficultorApp.CaficultorHelper.id (), "Caficultor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CaficultorApp.Caficultor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CaficultorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CaficultorApp.Caficultor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CaficultorApp.Caficultor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CaficultorApp.Caficultor)
      return (CaficultorApp.Caficultor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CaficultorApp._CaficultorStub stub = new CaficultorApp._CaficultorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CaficultorApp.Caficultor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CaficultorApp.Caficultor)
      return (CaficultorApp.Caficultor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CaficultorApp._CaficultorStub stub = new CaficultorApp._CaficultorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
