package CaficultorApp;


/**
* CaficultorApp/Caficultor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Caficultor.idl
* lunes 20 de mayo de 2019 12:19:22 AM COT
*/

public interface Caficultor extends CaficultorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Caficultor
