package CaficultorApp;


/**
* CaficultorApp/Caficultor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from caficultor.idl
* domingo 12 de mayo de 2019 10:01:11 PM COT
*/

public interface Caficultor extends CaficultorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Caficultor
