package CaficultorApp;


/**
* CaficultorApp/CaficultorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from caficultor.idl
* domingo 12 de mayo de 2019 10:01:11 PM COT
*/

public abstract class CaficultorPOA extends org.omg.PortableServer.Servant
 implements CaficultorApp.CaficultorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarPersona", new java.lang.Integer (0));
    _methods.put ("actualizarPersona", new java.lang.Integer (1));
    _methods.put ("eliminarPersona", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CaficultorApp/Caficultor/insertarPersona
       {
         int identificacion = in.read_long ();
         char tipo_identificacion = in.read_char ();
         String nombres = in.read_wstring ();
         String apellidos = in.read_wstring ();
         int telefono = in.read_long ();
         String direccion = in.read_wstring ();
         int ubicacion = in.read_long ();
         char sexo = in.read_char ();
         char estado = in.read_char ();
         boolean $result = false;
         $result = this.insertarPersona (identificacion, tipo_identificacion, nombres, apellidos, telefono, direccion, ubicacion, sexo, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CaficultorApp/Caficultor/actualizarPersona
       {
         int identificacion = in.read_long ();
         char tipo_identificacion = in.read_char ();
         String nombres = in.read_wstring ();
         String apellidos = in.read_wstring ();
         int telefono = in.read_long ();
         String direccion = in.read_wstring ();
         int ubicacion = in.read_long ();
         char sexo = in.read_char ();
         char estado = in.read_char ();
         boolean $result = false;
         $result = this.actualizarPersona (identificacion, tipo_identificacion, nombres, apellidos, telefono, direccion, ubicacion, sexo, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CaficultorApp/Caficultor/eliminarPersona
       {
         int identificacion = in.read_long ();
         boolean $result = false;
         $result = this.eliminarPersona (identificacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // CaficultorApp/Caficultor/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CaficultorApp/Caficultor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Caficultor _this() 
  {
    return CaficultorHelper.narrow(
    super._this_object());
  }

  public Caficultor _this(org.omg.CORBA.ORB orb) 
  {
    return CaficultorHelper.narrow(
    super._this_object(orb));
  }


} // class CaficultorPOA
