package CaficultorApp;


/**
* CaficultorApp/CaficultorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Caficultor.idl
* lunes 20 de mayo de 2019 12:19:22 AM COT
*/

public abstract class CaficultorPOA extends org.omg.PortableServer.Servant
 implements CaficultorApp.CaficultorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarCaficultor", new java.lang.Integer (0));
    _methods.put ("actualizarCaficultor", new java.lang.Integer (1));
    _methods.put ("eliminarCaficultor", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CaficultorApp/Caficultor/insertarCaficultor
       {
         int caf_identificacion = in.read_long ();
         String caf_tipo_identificacion = in.read_wstring ();
         String caf_nombres = in.read_wstring ();
         String caf_apellidos = in.read_wstring ();
         int caf_telefono = in.read_long ();
         String caf_direccion = in.read_wstring ();
         String caf_email = in.read_wstring ();
         int caf_id_ubicacion = in.read_long ();
         String caf_sexo = in.read_wstring ();
         String caf_estado = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarCaficultor (caf_identificacion, caf_tipo_identificacion, caf_nombres, caf_apellidos, caf_telefono, caf_direccion, caf_email, caf_id_ubicacion, caf_sexo, caf_estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CaficultorApp/Caficultor/actualizarCaficultor
       {
         int caf_identificacion = in.read_long ();
         String caf_tipo_identificacion = in.read_wstring ();
         String caf_nombres = in.read_wstring ();
         String caf_apellidos = in.read_wstring ();
         int caf_telefono = in.read_long ();
         String caf_direccion = in.read_wstring ();
         int caf_id_ubicacion = in.read_long ();
         String caf_email = in.read_wstring ();
         String caf_sexo = in.read_wstring ();
         String caf_estado = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarCaficultor (caf_identificacion, caf_tipo_identificacion, caf_nombres, caf_apellidos, caf_telefono, caf_direccion, caf_id_ubicacion, caf_email, caf_sexo, caf_estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CaficultorApp/Caficultor/eliminarCaficultor
       {
         int caf_identificacion = in.read_long ();
         boolean $result = false;
         $result = this.eliminarCaficultor (caf_identificacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // CaficultorApp/Caficultor/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CaficultorApp/Caficultor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Caficultor _this() 
  {
    return CaficultorHelper.narrow(
    super._this_object());
  }

  public Caficultor _this(org.omg.CORBA.ORB orb) 
  {
    return CaficultorHelper.narrow(
    super._this_object(orb));
  }


} // class CaficultorPOA
