package CaficultorApp;


/**
* CaficultorApp/CaficultorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Caficultor.idl
* lunes 20 de mayo de 2019 12:19:22 AM COT
*/

public interface CaficultorOperations 
{
  boolean insertarCaficultor (int caf_identificacion, String caf_tipo_identificacion, String caf_nombres, String caf_apellidos, int caf_telefono, String caf_direccion, String caf_email, int caf_id_ubicacion, String caf_sexo, String caf_estado);
  boolean actualizarCaficultor (int caf_identificacion, String caf_tipo_identificacion, String caf_nombres, String caf_apellidos, int caf_telefono, String caf_direccion, int caf_id_ubicacion, String caf_email, String caf_sexo, String caf_estado);
  boolean eliminarCaficultor (int caf_identificacion);
  void shutdown ();
} // interface CaficultorOperations
