package CaficultorApp;

/**
* CaficultorApp/CaficultorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from caficultor.idl
* domingo 12 de mayo de 2019 10:01:11 PM COT
*/

public final class CaficultorHolder implements org.omg.CORBA.portable.Streamable
{
  public CaficultorApp.Caficultor value = null;

  public CaficultorHolder ()
  {
  }

  public CaficultorHolder (CaficultorApp.Caficultor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CaficultorApp.CaficultorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CaficultorApp.CaficultorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CaficultorApp.CaficultorHelper.type ();
  }

}
