package ProductoApp;


/**
* ProductoApp/Producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 27 de mayo de 2019 06:01:45 PM COT
*/

public interface Producto extends ProductoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Producto
