package ProductoApp;


/**
* ProductoApp/ProductoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 27 de mayo de 2019 06:01:45 PM COT
*/

public interface ProductoOperations 
{
  boolean insertarProducto (int pro_id_producto, String pro_nombre, String pro_estado);
  boolean actualizarProducto (int pro_id_producto, String pro_nombre, String pro_estado);
  boolean eliminarProducto (int pro_id_producto);
  void shutdown ();
} // interface ProductoOperations
